### ISSUE TITLE
Which elm version?

### ISSUE THREAD

**Issue by chrisfcarroll** [toastal/Did-You-Get-The-Message-Commanding-the-New-Elm-Architecture#1]
I started with npm install, and elm-reactor didn't work (because I didn't have elm installed?). I tried npm install -g elm and that worked until I hit a web page that told me it relied on 0.17.1 and I had 18. I tried npm uninstall and then npm install elm@0.17.1 and it wouldn’t build because 
```
elm package install -y
elm-package: elm-stuff/exact-dependencies.json: openBinaryFile: does not exist (No such file or directory)
```
any thoughts?
OS X 10.12

**Comment by toastal** [comment]
Yeah I saw the same. Well, I just upgraded it to 0.18 so it's all good.

**Comment by chrisfcarroll** [comment]
Yay, thank you,
